name: pc-on

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Enable Terminal Services 
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop in Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set User Password
      run: |
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password
        
    - name: Create OpenVPN Connection
      run: |
        # Install OpenVPN silently
        choco install openvpn -y --force --accept-license
        
        # Wait for install to complete
        Start-Sleep -Seconds 30
        
        # Download config file (use raw GitHub URL)
        $configUrl = "https://raw.githubusercontent.com/molinabdellah-beep/fantastic-adventure/main/mrabdellahshop.first.ovpn"
        $configPath = "$env:ProgramFiles\OpenVPN\config\client.ovpn"
        
        # Create config directory if needed
        New-Item -ItemType Directory -Path "$env:ProgramFiles\OpenVPN\config" -Force
        
        # Download the config
        Invoke-WebRequest -Uri $configUrl -OutFile $configPath
        
        # Connect to VPN (runs in background)
        & "$env:ProgramFiles\OpenVPN\bin\openvpn.exe" --config "$configPath"
