name: pc-on

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Enable Terminal Services 
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop in Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set User Password
      run: |
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password

    - name: Create OpenVPN Connection
      shell: pwsh
      run: |
        # Install OpenVPN silently
        choco install openvpn -y --force --accept-license

        # Wait for install to complete
        Start-Sleep -Seconds 30

        # Download config file
        $configUrl = "https://raw.githubusercontent.com/molinabdellah-beep/fantastic-adventure/main/cfrt.first.ovpn"
        $configDir = "$env:ProgramFiles\OpenVPN\config"
        $configPath = "$configDir\client.ovpn"

        # Create config directory if needed
        if (!(Test-Path $configDir)) {
          New-Item -ItemType Directory -Path $configDir -Force
        }

        # Download the config
        Invoke-WebRequest -Uri $configUrl -OutFile $configPath

        # Connect to VPN (foreground, waits for completion)
        $exe = "$env:ProgramFiles\OpenVPN\bin\openvpn.exe"
        & $exe --config $configPath
