name: Create New File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create file
        run: |
          echo "Hello, World!" > new-file.txt
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add new-file.txt
          git commit -m "Add new file"
          git push
